### ISSUE TITLE
Support for HTTPS

### ISSUE THREAD

**Issue by Poeticode** [pips-/shuri#3]
Noticed that the shortened URL only uses http. I'll probably submit a PR later to let the short URL use https if `$_SERVER['HTTPS'] == true`, though I hear that's not 100% reliable for some PHP installations.

**Comment by pips-** [comment]
On 2018-04-26 19:08:09 +0000, Silas wrote:
> Noticed that the shortened URL only uses http. I'll probably submit a PR later to let the short URL use https if `$_SERVER['HTTPS'] == true`, though I hear that's not 100% reliable for some PHP installations.

It should work with https too, nothing in the script force the use of
http:// except the provided URL after shortening is http:// indeed.

Maybe we can use the construct "//" in the provided link, which let the
browser infer the scheme based on the current page?

-- 
Simon Lieb

**Comment by Poeticode** [comment]
Ah, that's an even better solution than checking the HTTPS variable.

**Comment by Poeticode** [comment]
I tried it out, and it seems the QR code may not work as a URL properly. Some readers require http:// or https:// to properly handle it as a link.

my.domain.com/page -> some QR code scanners treat it as a string, some as a URL
//my.domain.com/page -> All of my QR code scanners treat it as a string
